BUILD: adjust scripts and Make files for module inclusion (fixes #86)
- default build into FOAM_USER_{APPBIN,LIBBIN} unless otherwise
  specified by the module prefix.

- Handle development version of openfoam.com properly.
  Uses the API value, which is more reliable than anything
  coming from WM_PROJECT_VERSION

- Use AllwmakeParseArguments where available.
  Supports various options.
  Eg,

     ./Allwmake -s -j -l -prefix=openfoam

  to build targets directly into the OpenFOAM APPBIN, LIBBIN
  instead of user locations

diff --git a/TurbulenceModels/Allwmake b/TurbulenceModels/Allwmake
--- a/TurbulenceModels/Allwmake
+++ b/TurbulenceModels/Allwmake
@@ -1,9 +1,15 @@
 #!/bin/sh
-cd ${0%/*} || exit 1    # run from this directory
+cd "${0%/*}" || exit                            # Run from this directory
+#------------------------------------------------------------------------------
 set -x
 
 turbulenceModels/Allwmake
 
-wallFunctions/Allwmake
+if [ -f wallFunctions/Allwmake ]
+then
+    wallFunctions/Allwmake
+else
+    echo "Missing: wallFunctions/Allwmake"
+fi
 
-# ----------------------------------------------------------------- end-of-file
+#------------------------------------------------------------------------------
